### ISSUE TITLE
Question: code / documentation of `struct_tools`

### ISSUE THREAD

**Issue by dafeda** [patnr/HistoryMatching#4]
Hi,

any plans on releasing the code for `struct_tools`?

The objects in `struct_tools` seem simple enough, but cause a bit of friction due to lack of documentation and / or code.

Thanks

https://github.com/patricknraanes/HistoryMatching/blob/a0a17738c426d2c4b7efd7d798002167cac7ee8d/simulator/__init__.py#L24

**Comment by patnr** [comment]
Good point. Now available here:

https://github.com/patricknraanes/struct-tools
